### ISSUE TITLE
JSON.parse error

### ISSUE THREAD

**Issue by Seraaron** [lukstei/reddit-hyped-stocks#1]
Hi there, thanks for making this, looks really cool!

Unfortunately, I have an error. The error says:
`Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

I built my clone on Windows 10 using python and node.js, and set up the API with reddit as your instructions described. 

while installing the pre-requisites i also recieved an error after doing `npm i` which told me on of the installed things had a vulnerability and should be rolled back or updated, so i just updated... not sure if that specific version was critical?

**Comment by wghubcl** [comment]
Hi, I seem to have the same problem.

I will attach the log entry of the Flask app for the UI error.
[log.txt](https://github.com/lukstei/reddit-hyped-stocks/files/6155143/log.txt)

The error happens on request:

HTTP GET ":5000/scores"
HTTP error code: 500
The text "Internal Server Error" is returned (and can't be parsed as JSON)

I have tried both new data and data.db.example.

The other call to /tickerClassifications returns "null" with a status 200.

Is there a simple way to fix this?

**Comment by lukstei** [comment]
The problem seems to be that the example data is already a few days old, therefore we get index errors - either you collect your own data or use the provided one which can be downloaded at https://drive.google.com/file/d/12aAc35F5a0_doGE7Af8xsukRyNKPo1g0/view?usp=sharing (see updated Readme)

**Comment by wghubcl** [comment]
Thanks a lot! That worked.

If I read correctly, the script loads a maximum of 1000 posts that have been posted during the last 7 days. What would be the best schedule to run load_data.py? Is it useful to configure time_filter="day" and to run it every day?

**Comment by lukstei** [comment]
Great!

I personally run it every hour, but running it daily should be sufficient
